apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: cloud-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend
        image: acrccullquicondo01.azurecr.io/cloud-backend:1.4
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mysql-secret
            name: storage-secret

